sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc
  - clang

cache:
  directories:
  - download-cache

env:
  global:
    - JOBS=3
    - NGX_BUILD_JOBS=$JOBS
  matrix:
    - TEST_MODE=1
    - TEST_MODE=2
install:
  - git clone https://github.com/openresty/lua-cjson.git

script:
  - echo "hi"
